/** Default parameters per node type — matches PyTorch nn.Module constructors. */

export const NODE_DEFAULTS: Record<string, Record<string, any>> = {
  Input: {},
  // Convolution Layers
  Conv1d: { in_channels: 1, out_channels: 16, kernel_size: 3 },
  Conv2d: { in_channels: 3, out_channels: 64, kernel_size: 3, padding: 1 },
  Conv3d: { in_channels: 1, out_channels: 16, kernel_size: 3 },
  ConvTranspose1d: { in_channels: 16, out_channels: 1, kernel_size: 3 },
  ConvTranspose2d: { in_channels: 64, out_channels: 3, kernel_size: 4, stride: 2, padding: 1 },
  ConvTranspose3d: { in_channels: 16, out_channels: 1, kernel_size: 3 },
  LazyConv1d: { out_channels: 16, kernel_size: 3 },
  LazyConv2d: { out_channels: 64, kernel_size: 3 },
  LazyConv3d: { out_channels: 16, kernel_size: 3 },
  LazyConvTranspose1d: { out_channels: 1, kernel_size: 3 },
  LazyConvTranspose2d: { out_channels: 3, kernel_size: 3 },
  LazyConvTranspose3d: { out_channels: 1, kernel_size: 3 },
  Unfold:{ kernel_size: 3 },
  Fold: { output_size: 64, kernel_size: 3 },
  // Pooling
  MaxPool1d: { kernel_size: 2 },
  MaxPool2d: { kernel_size: 2 },
  MaxPool3d: { kernel_size: 2 },
  MaxUnpool1d: { kernel_size: 2 },
  MaxUnpool2d: { kernel_size: 2 },
  MaxUnpool3d: { kernel_size: 2 },
  AvgPool1d: { kernel_size: 2 },
  AvgPool2d: { kernel_size: 2 },
  AvgPool3d: { kernel_size: 2 },
  FractionalMaxPool2d: { kernel_size: 2 },
  FractionalMaxPool3d: { kernel_size: 2 },
  LPPool1d: { norm_type: 2, kernel_size: 2 },
  LPPool2d: { norm_type: 2, kernel_size: 2 },
  LPPool3d: { norm_type: 2, kernel_size: 2 },
  AdaptiveMaxPool1d: { output_size: 1 },
  AdaptiveMaxPool2d: { output_size: 1 },
  AdaptiveMaxPool3d: { output_size: 1 },
  AdaptiveAvgPool1d: { output_size: 1 },
  AdaptiveAvgPool2d: { output_size: 1 },
  AdaptiveAvgPool3d: { output_size: 1 },
  // Non-linear Activations (weighted sum, nonlinearity)
  ELU: {},
  Hardshrink: {},
  Hardsigmoid: {},
  Hardtanh: {},
  Hardswish: {},
  LeakyReLU: {},
  LogSigmoid: {},
  PReLU: {},
  ReLU6: {},
  RReLU: {},
  MultiheadAttention: { embed_dim: 512, num_heads: 8, batch_first: true },
  SELU: {},
  CELU: {},
  SiLU: {},
  Mish: {},
  Softplus: {},
  Softshrink: {},
  Softsign: {},
  ReLU: {},
  GELU: {},
  Sigmoid: {},
  Tanh: {},
  Tanhshrink: {},
  Threshold: { threshold: -3, value: 3 },
  GLU: {},
  // Non-linear Activations (other)
  Softmin: {},
  Softmax: {},
  Softmax2d: {},
  LogSoftmax: {},
  AdaptiveLogSoftmaxWithLoss: { in_features: 128, n_classes: 1000, cutoffs: [20, 100] },
  // Normalization Layers
  BatchNorm1d: { num_features: 64 },
  BatchNorm2d: { num_features: 64 },
  BatchNorm3d: { num_features: 64 },
  LazyBatchNorm1d: {},
  LazyBatchNorm2d: {},
  LazyBatchNorm3d: {},
  GroupNorm: { num_groups: 8, num_channels: 64 },
  SyncBatchNorm: { num_features: 256 },
  InstanceNorm1d: { num_features: 256 },
  InstanceNorm2d: { num_features: 256 },
  InstanceNorm3d: { num_features: 256 },
  LazyInstanceNorm1d: {},
  LazyInstanceNorm2d: {},
  LazyInstanceNorm3d: {},
  LayerNorm: { normalized_shape: [256] },
  LocalResponseNorm: { size: 16 },
  RMSNorm: { normalized_shape: 16 },
  // Recurrent Layers — batch_first matches the (B, Seq, D) shape convention
  // (RNNBase removed: abstract base class, not executable)
  RNN: { input_size: 256, hidden_size: 128, batch_first: true },
  LSTM: { input_size: 256, hidden_size: 128, batch_first: true },
  GRU: { input_size: 256, hidden_size: 128, batch_first: true },
  RNNCell: { input_size: 256, hidden_size: 128 },
  LSTMCell: { input_size: 256, hidden_size: 128 },
  GRUCell: { input_size: 256, hidden_size: 128 },
  // Transformer Layers — TransformerEncoder/Decoder take flat layer params
  // plus num_layers/norm; the backend composes the stack (layers/registry.py).
  Transformer: {
    d_model: 512, nhead: 8, num_encoder_layers: 6, num_decoder_layers: 6,
    dim_feedforward: 2048, dropout: 0.1, batch_first: true,
  },
  TransformerEncoder: {
    d_model: 512, nhead: 8, dim_feedforward: 2048, dropout: 0.1,
    batch_first: true, num_layers: 6, norm: false,
  },
  TransformerDecoder: {
    d_model: 512, nhead: 8, dim_feedforward: 2048, dropout: 0.1,
    batch_first: true, num_layers: 6, norm: false,
  },
  TransformerEncoderLayer: { d_model: 512, nhead: 8, batch_first: true },
  TransformerDecoderLayer: { d_model: 512, nhead: 8, batch_first: true },
  // Linear Layers
  Identity: {},
  Linear: { in_features: 256, out_features: 128 },
  Bilinear: { in1_features: 128, in2_features: 256, out_features: 128 },
  LazyLinear: { out_features: 128 },
  // Dropout Layers
  Dropout: { p: 0.5 },
  Dropout1d: { p: 0.5 },
  Dropout2d: { p: 0.5 },
  Dropout3d: { p: 0.5 },
  AlphaDropout: { p: 0.5 },
  FeatureAlphaDropout: { p: 0.5 },
  // Sparse Layers
  Embedding: { num_embeddings: 10000, embedding_dim: 256 },
  EmbeddingBag: { num_embeddings: 10000, embedding_dim: 256 },
  // Vision Ops
  PixelShuffle: { upscale_factor: 2 },
  PixelUnshuffle: { downscale_factor: 2 },
  // Reduction Ops — no learnable params
  Add: {},
  Subtract: {},
  Multiply: {},
  Divide: {},
  Concat: { dim: -1 },
  Stack: { dim: 0 },
  // Tensor Ops
  Flatten: { start_dim: 1 },
  Reshape: { shape: [-1, 256] },
  Permute: { dims: [0, 2, 1] },
  Transpose: { dim0: 0, dim1: 1 },
  View: { shape: [-1, 256] },
  Squeeze: {},
  Unsqueeze: { dim: 0 },
  Split: { split_size_or_sections: [128, 128], dim: -1 },
  // Block
  Block: {},
  // HuggingFace pseudo-types (type is used for ReactFlow, hf_model/hf_config for backend)
  //HF_Pretrained: {},
  //HF_Config: {},
  // Custom
  custom: {},
};
